global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-api'
    static_configs:
      - targets: ['flask-api:5000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
